In [11]:
import torch
import numpy

In [13]:
# Создаем тензор
x = torch.rand([3, 4])
x = torch.zeros([3, 4])
x = torch.ones([3, 4, 3])

# print x
#x = torch.eye(3, 4)

x = torch.Tensor(
[[1,  2,  3,  4],
 [5,  6,  7,  8],
 [9, 10, 11, 12]])

print(x, '<- tensor\n')
print(x.size(), '<- tensor size\n')
print(x.size(0), '<- dimension size\n')
print(x[1:, 1:3], '<- slicing support\n')

tensor([[  1.,   2.,   3.,   4.],
        [  5.,   6.,   7.,   8.],
        [  9.,  10.,  11.,  12.]]) <- tensor

torch.Size([3, 4]) <- tensor size

3 <- dimension size

tensor([[  6.,   7.],
        [ 10.,  11.]]) <- slicing support



In [14]:
# Копирование (по ссылке и глубокое)
y = x

y[1, :] = 1
print(x, '\n', y, '<- shallow copy\n')

y = x.clone()
y[1, :] = 2
print(x, '\n', y, '<- deep copy')

tensor([[  1.,   2.,   3.,   4.],
        [  1.,   1.,   1.,   1.],
        [  9.,  10.,  11.,  12.]]) 
 tensor([[  1.,   2.,   3.,   4.],
        [  1.,   1.,   1.,   1.],
        [  9.,  10.,  11.,  12.]]) <- shallow copy

tensor([[  1.,   2.,   3.,   4.],
        [  1.,   1.,   1.,   1.],
        [  9.,  10.,  11.,  12.]]) 
 tensor([[  1.,   2.,   3.,   4.],
        [  2.,   2.,   2.,   2.],
        [  9.,  10.,  11.,  12.]]) <- deep copy


In [15]:
# Математические операции (стандартные поэлементные)
print(x + y, x * y, x / y, x - y,)
print(x % y, x**2, x**y, '<- basic math')

tensor([[  2.,   4.,   6.,   8.],
        [  3.,   3.,   3.,   3.],
        [ 18.,  20.,  22.,  24.]]) tensor([[   1.,    4.,    9.,   16.],
        [   2.,    2.,    2.,    2.],
        [  81.,  100.,  121.,  144.]]) tensor([[ 1.0000,  1.0000,  1.0000,  1.0000],
        [ 0.5000,  0.5000,  0.5000,  0.5000],
        [ 1.0000,  1.0000,  1.0000,  1.0000]]) tensor([[ 0.,  0.,  0.,  0.],
        [-1., -1., -1., -1.],
        [ 0.,  0.,  0.,  0.]])
tensor([[ 0.,  0.,  0.,  0.],
        [ 1.,  1.,  1.,  1.],
        [ 0.,  0.,  0.,  0.]]) tensor([[   1.,    4.,    9.,   16.],
        [   1.,    1.,    1.,    1.],
        [  81.,  100.,  121.,  144.]]) tensor([[ 1.0000e+00,  4.0000e+00,  2.7000e+01,  2.5600e+02],
        [ 1.0000e+00,  1.0000e+00,  1.0000e+00,  1.0000e+00],
        [ 3.8742e+08,  1.0000e+10,  2.8531e+11,  8.9161e+12]]) <- basic math


In [18]:
# Более сложные операции
print(torch.exp(x))
print(torch.log(x))
print(torch.sin(x))

tensor([[ 2.7183e+00,  7.3891e+00,  2.0086e+01,  5.4598e+01],
        [ 2.7183e+00,  2.7183e+00,  2.7183e+00,  2.7183e+00],
        [ 8.1031e+03,  2.2026e+04,  5.9874e+04,  1.6275e+05]])
tensor([[ 0.0000,  0.6931,  1.0986,  1.3863],
        [ 0.0000,  0.0000,  0.0000,  0.0000],
        [ 2.1972,  2.3026,  2.3979,  2.4849]])
tensor([[ 0.8415,  0.9093,  0.1411, -0.7568],
        [ 0.8415,  0.8415,  0.8415,  0.8415],
        [ 0.4121, -0.5440, -1.0000, -0.5366]])


In [19]:
x > 3

tensor([[ 0,  0,  0,  1],
        [ 0,  0,  0,  0],
        [ 1,  1,  1,  1]], dtype=torch.uint8)

In [17]:
# Логические операции
y = x[x > 3]
print(y)
y = (x > 3)
print(y)

tensor([  4.,   9.,  10.,  11.,  12.])
tensor([[ 0,  0,  0,  1],
        [ 0,  0,  0,  0],
        [ 1,  1,  1,  1]], dtype=torch.uint8)


In [21]:
# Переопределение типа
x = x.float()
print(x)
x = x.double()
print(x)
x = x.int()
print(x)
x = x.float()

tensor([[  1.,   2.,   3.,   4.],
        [  1.,   1.,   1.,   1.],
        [  9.,  10.,  11.,  12.]])
tensor([[  1.,   2.,   3.,   4.],
        [  1.,   1.,   1.,   1.],
        [  9.,  10.,  11.,  12.]], dtype=torch.float64)
tensor([[  1,   2,   3,   4],
        [  1,   1,   1,   1],
        [  9,  10,  11,  12]], dtype=torch.int32)


In [24]:
# Взаимодействие с Numpy
x = numpy.array([[1, 2, 3, 4], [4, 3, 2, 1]])
print(x)
x = torch.from_numpy(x)
print(x)
x = x.numpy()
print(x)
x = torch.from_numpy(x).float().int().double()
print(x)

[[1 2 3 4]
 [4 3 2 1]]
tensor([[ 1,  2,  3,  4],
        [ 4,  3,  2,  1]])
[[1 2 3 4]
 [4 3 2 1]]
tensor([[ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]], dtype=torch.float64)


In [54]:
torch.cuda.is_available()

True

In [55]:
# Перемещение на GPU
import time
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
print(device, 'is avaliable')
x_cuda = x.to('cuda:0')
#x_cuda = x.to(device)
print(x_cuda, '<- CUDA Tensor!')
print(x)

cuda:0 is avaliable
tensor([[ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]], dtype=torch.float64, device='cuda:0') <- CUDA Tensor!
tensor([[ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]], dtype=torch.float64)


In [56]:
!pwd

/home/teacher/AI Boot Camp/deep_learning_course_2.0


In [57]:
!nvidia-smi

Tue Jul  3 12:45:21 2018       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.130                Driver Version: 384.130                   |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 107...  Off  | 00000000:01:00.0  On |                  N/A |
|  0%   47C    P8     7W / 180W |    767MiB /  8105MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU  

In [58]:
x_cuda = x.to('cuda:0')

In [62]:
# CPU time
%timeit y = (x - x + x*10.0) ** 2

12.2 µs ± 48.4 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [60]:
x.dtype

torch.float64

In [63]:
# GPU time
%timeit y_cuda = (x_cuda - x_cuda + x_cuda * 10.0) ** 2

51.1 µs ± 98.6 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [64]:
x_cuda.dtype

torch.float64

In [67]:
# Автоматическое (символьное) дифференциирование (обратное распространение градиента) (случай скаляра)
import torch.autograd

x = torch.tensor(
    [[1,  2,  3,  4],
     [5,  6,  7,  8],
     [9, 10, 11, 12]], requires_grad=True)

formula = (x ** 2).sum().median()
print(formula)
formula.backward()

print(x.grad, '<- gradient')

tensor(650)
tensor([[  2,   4,   6,   8],
        [ 10,  12,  14,  16],
        [ 18,  20,  22,  24]]) <- gradient


In [68]:
# Как тензор хранит свою историю
print(formula.grad_fn)
print(formula.grad_fn.next_functions[0][0])
print(formula.grad_fn.next_functions[0][0].next_functions[0][0])
print(formula.grad_fn.next_functions[0][0].next_functions[0][0].next_functions[0][0])

## Задание 1
Написать и вычислить бинарную кросс-энтопию для векторов target и probs при помощи средств pytorch.
Бинарная кросс-энтропия вычисляется:

$$BCE(t, p) = - \sum_i t_i \log(p_i) + (1 - t_i) \log(1 - p_i)$$

target = (0, 0, 0, 0, 1, 1, 1, 1)
probs = (0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8)

Какой из элементов суммы дает наибольший вклад в функцию потерь?

In [70]:
target = (0, 0, 0, 0, 1, 1, 1, 1)
probs = (0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8)
BCE = 0
for number in [0, 1, 2, 3, 4, 5, 6, 7]:
    BCE = BCE - target[i]*log

In [169]:
t = torch.tensor([0, 0, 0, 0, 1, 1, 1, 1]).float()
p = torch.tensor([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8],requires_grad=True)

In [170]:
def BCE(t,p):
    BCE= -(t*torch.log(p)+(1-t)*torch.log(1-p)).sum()
    return (BCE)

In [172]:
BCE(t,p)

tensor(2.9798)

In [173]:
(-t*torch.log(p)-(1-t)*torch.log(1-p)).argmax()

tensor(4)

# Задание 2

Логистическая регрессия минимизирует функцию бинарной кросс-энтропии (BCE), предполагая, что
$$p_i = \sigma (< w_i, x_i >)$$
где $w_i$ -- веса свойств объектов, $x_i$ -- свойства объектов. Пусть $\vec{x} = (1, x_1, x_2)$. Подставить вероятности в выражение $BCE$ и найти производную $BCE$ по весам.
Вычислить производную в случае двух объектов (любым способом, можно посчитать руками, можно написать скрипт):

$t = 1, x = (1, 1, 1)$

$t = 0, x = (1, 0, 1)$

В точке w = (0, 0, 0).

Совпадает ли результат явного вычисления с результатом работы функции backward?

In [244]:
t_2 = torch.tensor([1, 0], requires_grad=True, dtype = torch.float32)

In [245]:
import math
def sigma(x_1,x_2):
    sigma = torch.Tensor( (1 / (1 + torch.exp(x_1)), 1 / (1 + torch.exp(x_1)) ) )
    return sigma

In [246]:
x1 = torch.tensor([[1,  1,  1]], dtype = torch.float32)
torch.log(x1)

tensor([[ 0.,  0.,  0.]])

In [249]:
import torch.autograd

x_1 = torch.tensor(
    [1,  1,  1], requires_grad=True, dtype = torch.float32)
x_2 = torch.tensor(
    [1,  0,  1], requires_grad=True, dtype = torch.float32)
w = torch.tensor(
    [0,  0,  0], requires_grad=True, dtype = torch.float32)

formula = BCE(t_2, sigma((x_1 * w).sum(),(x_2 * w).sum()))
print(formula)
formula.backward()

print(x_1.grad, x_2.grad, '<- gradient')

tensor(1.3863)
None None <- gradient


In [200]:
import torch.autograd

x_1 = torch.tensor(
    [1,  1,  1], requires_grad=True, dtype = torch.float32)
x_2 = torch.tensor(
    [1,  0,  1], requires_grad=True, dtype = torch.float32)
w = torch.tensor(
    [0,  0,  0], requires_grad=True, dtype = torch.float32)

formula = BCE(t_2, sigma((x_1 * w).sum(),(x_2 * w).sum()))
print(formula)
formula.backward()

print(x_1.grad, x_2.grad, '<- gradient')

TypeError: mul() received an invalid combination of arguments - got (builtin_function_or_method), but expected one of:
 * (Tensor other)
      didn't match because some of the arguments have invalid types: (!builtin_function_or_method!)
 * (float other)
      didn't match because some of the arguments have invalid types: (!builtin_function_or_method!)


## Задание 3

Средствами pytorch реализовать алгоритм градиентного спуска.

При помощи этого алгоритма найти минимум функций:
$x^2 + y^2$ с начальным приближением $x_0 = 10, y_0 = 5$, 

$0.5 \log x + 0.5 \log (1 - x)$ с начальным приближением $x_0 = 0.9$, 

$x^2 + 10 y^2 + 2xy$, с начальным приближением $x_0 = 10.0, y_0 = 10.0$

## Задание 4


При помощи алгоритма градиентного спуска оптимизировать вектор probs при фиксированном векторе target из задания 1.
Рассмотреть два варианта решения задачи: 

1) при помощи CPU 

2) при помощи GPU

Получилось ли ускорить процесс при помощи GPU? Обсудить, почему.

О градиентном спуске:
https://ru.wikipedia.org/wiki/%D0%93%D1%80%D0%B0%D0%B4%D0%B8%D0%B5%D0%BD%D1%82%D0%BD%D1%8B%D0%B9_%D1%81%D0%BF%D1%83%D1%81%D0%BA